#include <Arduino.h>

// #include "main.h"
#include "states/StateInit.h"
#include "states/context.h"


#define LIFTSERVONWPIN 8
#define LIFTSERVONEPIN 9
#define LIFTSERVOSEPIN 10
#define TILTSERVOXPIN  5
#define TILTSERVOYPIN  6

#define LIMITSWITCHNWPIN  A0
#define LIMITSWITCHNEPIN  A1
#define LIMITSWITCHSEPIN  A2
#define BUTTONPIN		  2
#define JOYSTICKBUTTONPIN 3
#define JOYSTICKXPIN	  A3
#define JOYSTICKYPIN	  A4
#define COININTERRUPTPIN  12
#define WININTERRUPTPIN	  13

#define DISPLAYLATCHPIN 0
#define DISPLAYCLOCKPIN 1
#define DISPLAYDATAPIN	4


Context* ctx;


// ============ MAIN ============

void setup() {
	Serial.begin(9600);
	Serial.println("Ran!");

	ctx = new Context(new InitState(), TILTSERVOXPIN, TILTSERVOYPIN, LIFTSERVONWPIN, LIFTSERVONEPIN, LIFTSERVOSEPIN,
					  LIMITSWITCHNWPIN, LIMITSWITCHNEPIN, LIMITSWITCHSEPIN, BUTTONPIN, JOYSTICKXPIN, JOYSTICKYPIN,
					  JOYSTICKBUTTONPIN, COININTERRUPTPIN, WININTERRUPTPIN, DISPLAYLATCHPIN, DISPLAYCLOCKPIN,
					  DISPLAYDATAPIN);
}

void loop() { ctx->update(); }